import React from "react";

import {
  FiPrinter,
  FiUser,
  FiMapPin,
  FiDollarSign,
  FiCalendar,
} from "react-icons/fi";

import Modal from "../modal/Modal";

const rowStyle = {
  display: "flex",
  justifyContent: "space-between",
  padding: ".9rem 0",
  borderBottom: "1px solid #E2E8F0",
};

const SalarySlipModal = ({
  open,
  worker,
  onClose,
}) => {

  if (!worker) return null;

  const grossSalary =
    worker.dailyWage *
    worker.daysWorked;

  const netSalary =
    grossSalary -
    worker.advance -
    worker.paid;

  const printSlip = () => {

    window.print();

  };

  return (

    <Modal
      open={open}
      title="Salary Slip"
      submitText="Print Slip"
      onClose={onClose}
      onSubmit={printSlip}
    >

      <div
        id="salary-slip"
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "1.5rem",
        }}
      >

        {/* Company */}

        <div
          style={{
            textAlign: "center",
          }}
        >

          <h2
            style={{
              margin: 0,
              color: "#0F172A",
            }}
          >

            Contractor Worker Management

          </h2>

          <p
            style={{
              color: "#64748B",
            }}
          >

            Salary Slip

          </p>

        </div>

        {/* Worker Info */}

        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "repeat(2,1fr)",
            gap: "1rem",
          }}
        >

          <div>

            <FiUser />

            {" "}

            {worker.name}

          </div>

          <div>

            <FiMapPin />

            {" "}

            {worker.site}

          </div>

          <div>

            <FiCalendar />

            {" "}

            {worker.daysWorked} Days

          </div>

          <div>

            <FiDollarSign />

            {" "}

            ₹{worker.dailyWage}/day

          </div>

        </div>

        {/* Salary Details */}

        <div>

          <div style={rowStyle}>

            <span>

              Gross Salary

            </span>

            <strong>

              ₹{grossSalary}

            </strong>

          </div>

          <div style={rowStyle}>

            <span>

              Advance

            </span>

            <strong>

              ₹{worker.advance}

            </strong>

          </div>

          <div style={rowStyle}>

            <span>

              Paid

            </span>

            <strong>

              ₹{worker.paid}

            </strong>

          </div>

          <div style={rowStyle}>

            <span>

              Remaining

            </span>

            <strong
              style={{
                color:
                  netSalary > 0
                    ? "#DC2626"
                    : "#16A34A",
              }}
            >

              ₹{netSalary}

            </strong>

          </div>

        </div>

        {/* Footer */}

        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            marginTop: "1rem",
          }}
        >

          <div>

            <small>

              Generated by Contractor Worker Management

            </small>

          </div>

          <button
            onClick={printSlip}
            style={{
              border: "none",
              background: "#2563EB",
              color: "#fff",
              padding: ".8rem 1.3rem",
              borderRadius: ".7rem",
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: ".5rem",
            }}
          >

            <FiPrinter />

            Print

          </button>

        </div>

      </div>

    </Modal>

  );

};

export default SalarySlipModal;