import Site from '../models/Site.js';
import User from '../models/User.js';

import logger from '../common/logger/logger.js';

import { faker } from '@faker-js/faker';

const SITES = [
  {
    siteCode: 'SITE001',
    siteName: 'DLF Tower',
    clientName: 'DLF Limited',
    projectName: 'DLF Tower Construction',
    address: 'Plot No. 25, Dwarka Expressway, Sector 104',
    city: 'Gurgaon',
    district: 'Gurugram',
    state: 'Haryana',
    pincode: '122018',
    contactPerson: 'Rajesh Malhotra',
    contactNumber: '9876543210',
    email: 'rajesh@dlf.com',
    description: 'Commercial tower construction project in Gurgaon.',
  },
  {
    siteCode: 'SITE002',
    siteName: 'Metro Project Phase 3',
    clientName: 'DMRC',
    projectName: 'Delhi Metro Phase 3 Expansion',
    address: 'Metro Depot, Sector 25, Noida',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201301',
    contactPerson: 'Amit Khanna',
    contactNumber: '9876543211',
    email: 'amit@dmrc.org',
    description: 'Delhi Metro Phase 3 expansion project.',
  },
  {
    siteCode: 'SITE003',
    siteName: 'Airport Terminal 2',
    clientName: 'DIAL',
    projectName: 'IGI Airport Terminal 2 Expansion',
    address: 'Palam Road, Near Airport',
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    pincode: '110037',
    contactPerson: 'Sanjay Verma',
    contactNumber: '9876543212',
    email: 'sanjay@dial.aero',
    description: 'Terminal 2 expansion at Indira Gandhi International Airport.',
  },
  {
    siteCode: 'SITE004',
    siteName: 'Industrial Plant Alpha',
    clientName: 'Reliance Industries',
    projectName: 'Reliance Industrial Plant Alpha',
    address: 'Industrial Area, Phase 1',
    city: 'Manesar',
    district: 'Gurugram',
    state: 'Haryana',
    pincode: '122051',
    contactPerson: 'Prakash Joshi',
    contactNumber: '9876543213',
    email: 'prakash@reliance.com',
    description: 'Industrial plant construction for Reliance Industries.',
  },
  {
    siteCode: 'SITE005',
    siteName: 'Metro City Mall',
    clientName: 'Metro Group',
    projectName: 'Metro City Mall Construction',
    address: 'NH-8, Near Toll Plaza',
    city: 'Gurgaon',
    district: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    contactPerson: 'Vikram Singh',
    contactNumber: '9876543214',
    email: 'vikram@metrogroup.com',
    description: 'Shopping mall construction project.',
  },
  {
    siteCode: 'SITE006',
    siteName: 'IT Park Building',
    clientName: 'Infosys',
    projectName: 'Infosys IT Park Building C',
    address: 'Sector 62, Noida',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201309',
    contactPerson: 'Anil Kapoor',
    contactNumber: '9876543215',
    email: 'anil@infosys.com',
    description: 'IT park building construction for Infosys.',
  },
  {
    siteCode: 'SITE007',
    siteName: 'Residential Complex Delta',
    clientName: 'Omaxe Ltd',
    projectName: 'Omaxe Residential Complex Delta',
    address: 'Plot 45, Dwarka, New Delhi',
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    pincode: '110078',
    contactPerson: 'Ravi Nath',
    contactNumber: '9876543216',
    email: 'ravi@omaxe.com',
    description: 'Residential complex construction project.',
  },
  {
    siteCode: 'SITE008',
    siteName: 'Highway Bridge Repair',
    clientName: 'NHAI',
    projectName: 'NH-48 Bridge Repair Project',
    address: 'NH-48, Kilometer 12',
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    pincode: '110001',
    contactPerson: 'Manoj Tiwari',
    contactNumber: '9876543217',
    email: 'manoj@nhai.gov.in',
    description: 'Bridge repair and maintenance on NH-48.',
  },
  {
    siteCode: 'SITE009',
    siteName: 'Hospital Wing Expansion',
    clientName: 'Apollo Hospitals',
    projectName: 'Apollo Hospital Wing B Expansion',
    address: 'Sarita Vihar, New Delhi',
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    pincode: '110076',
    contactPerson: 'Dr. Sunil Gupta',
    contactNumber: '9876543218',
    email: 'sunil@apollo.com',
    description: 'Hospital wing expansion project.',
  },
  {
    siteCode: 'SITE010',
    siteName: 'Warehouse Facility',
    clientName: 'Amazon',
    projectName: 'Amazon Fulfillment Center',
    address: 'Industrial Area, Bawana',
    city: 'Delhi',
    district: 'North West Delhi',
    state: 'Delhi',
    pincode: '110039',
    contactPerson: 'Kumar Singh',
    contactNumber: '9876543219',
    email: 'kumar@amazon.com',
    description: 'Fulfillment center warehouse construction.',
  },
  {
    siteCode: 'SITE011',
    siteName: 'School Building Project',
    clientName: 'Delhi Public School',
    projectName: 'DPS New Wing Construction',
    address: 'Sector 45, Noida',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201301',
    contactPerson: 'Mrs. Shalini Agarwal',
    contactNumber: '9876543220',
    email: 'shalini@dps.edu',
    description: 'New wing construction for Delhi Public School.',
  },
  {
    siteCode: 'SITE012',
    siteName: 'Hotel Grand Tower',
    clientName: 'Taj Hotels',
    projectName: 'Taj Hotel Grand Tower',
    address: 'Mahipalpur, New Delhi',
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    pincode: '110037',
    contactPerson: 'Rohit Malhotra',
    contactNumber: '9876543221',
    email: 'rohit@tajhotels.com',
    description: 'Hotel tower construction project.',
  },
  {
    siteCode: 'SITE013',
    siteName: 'Residential Township',
    clientName: 'DLF Homes',
    projectName: 'DLF Township Phase 5',
    address: 'Dwarka, Sector 22',
    city: 'Delhi',
    district: 'South West Delhi',
    state: 'Delhi',
    pincode: '110075',
    contactPerson: 'Anil Dhawan',
    contactNumber: '9876543222',
    email: 'anil@dlfhomes.com',
    description: 'Residential township development project.',
  },
  {
    siteCode: 'SITE014',
    siteName: 'Factory Unit 7',
    clientName: 'Honda Siel',
    projectName: 'Honda Manufacturing Unit 7',
    address: 'Manesar Industrial Area',
    city: 'Manesar',
    district: 'Gurugram',
    state: 'Haryana',
    pincode: '122051',
    contactPerson: 'Sanjeev Chopra',
    contactNumber: '9876543223',
    email: 'sanjeev@honda.com',
    description: 'New manufacturing unit construction.',
  },
  {
    siteCode: 'SITE015',
    siteName: 'Metro Station Construction',
    clientName: 'DMRC',
    projectName: 'Noida Metro Station',
    address: 'Noida Sector 62',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201309',
    contactPerson: 'Pramod Kumar',
    contactNumber: '9876543224',
    email: 'pramod@dmrc.org',
    description: 'Metro station construction project.',
  },
  {
    siteCode: 'SITE016',
    siteName: 'Data Center',
    clientName: 'Tata Communications',
    projectName: 'Tata Data Center Phase 2',
    address: 'Manesar, Haryana',
    city: 'Manesar',
    district: 'Gurugram',
    state: 'Haryana',
    pincode: '122051',
    contactPerson: 'Arun Mehta',
    contactNumber: '9876543225',
    email: 'arun@tatacom.com',
    description: 'Data center construction project.',
  },
  {
    siteCode: 'SITE017',
    siteName: 'Water Treatment Plant',
    clientName: 'Delhi Jal Board',
    projectName: 'WTP Okhla Phase 2',
    address: 'Okhla Industrial Area',
    city: 'Delhi',
    district: 'South East Delhi',
    state: 'Delhi',
    pincode: '110020',
    contactPerson: 'Sanjay Rastogi',
    contactNumber: '9876543226',
    email: 'sanjay@djb.gov.in',
    description: 'Water treatment plant expansion.',
  },
  {
    siteCode: 'SITE018',
    siteName: 'Shopping Complex',
    clientName: 'Future Group',
    projectName: 'Big Bazaar Mall',
    address: 'Rohini, Sector 15',
    city: 'Delhi',
    district: 'North Delhi',
    state: 'Delhi',
    pincode: '110085',
    contactPerson: 'Vijay Sharma',
    contactNumber: '9876543227',
    email: 'vijay@futuregroup.com',
    description: 'Shopping complex construction.',
  },
  {
    siteCode: 'SITE019',
    siteName: 'Office Building',
    clientName: 'Wipro',
    projectName: 'Wipro Office Noida',
    address: 'Sector 128, Noida',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201313',
    contactPerson: 'Rajiv Malhotra',
    contactNumber: '9876543228',
    email: 'rajiv@wipro.com',
    description: 'Corporate office building construction.',
  },
  {
    siteCode: 'SITE020',
    siteName: 'Stadium Renovation',
    clientName: 'Delhi Government',
    projectName: 'Jawaharlal Nehru Stadium Renovation',
    address: 'Bandra Kurla Complex',
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    pincode: '110001',
    contactPerson: 'Ajay Thakur',
    contactNumber: '9876543229',
    email: 'ajay@delhigovt.gov.in',
    description: 'Stadium renovation and upgrade project.',
  },
  {
    siteCode: 'SITE021',
    siteName: 'Solar Farm',
    clientName: 'Adani Green',
    projectName: 'Adani Solar Farm Phase 1',
    address: 'Rewari Road, Haryana',
    city: 'Rewari',
    district: 'Rewari',
    state: 'Haryana',
    pincode: '123401',
    contactPerson: 'Karan Patel',
    contactNumber: '9876543230',
    email: 'karan@adani.com',
    description: 'Solar farm construction project.',
  },
  {
    siteCode: 'SITE022',
    siteName: 'Bridge Construction',
    clientName: 'Government of UP',
    projectName: 'Yamuna Bridge Project',
    address: 'Near Yamuna River, Noida',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201301',
    contactPerson: 'Sanjeev Kumar',
    contactNumber: '9876543231',
    email: 'sanjeev@upgovt.gov.in',
    description: 'Bridge construction over Yamuna river.',
  },
  {
    siteCode: 'SITE023',
    siteName: 'Pharma Plant',
    clientName: 'Sun Pharma',
    projectName: 'Sun Pharma Manufacturing Plant',
    address: 'Dewas, Madhya Pradesh',
    city: 'Dewas',
    district: 'Dewas',
    state: 'Madhya Pradesh',
    pincode: '455332',
    contactPerson: 'Ramesh Iyer',
    contactNumber: '9876543232',
    email: 'ramesh@sunpharma.com',
    description: 'Pharmaceutical manufacturing plant construction.',
  },
  {
    siteCode: 'SITE024',
    siteName: 'Apartment Complex',
    clientName: 'Unitech Group',
    projectName: 'Unitech Grand Homes',
    address: 'Greater Noida, Sector 76',
    city: 'Greater Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201310',
    contactPerson: 'Deepak Uniyal',
    contactNumber: '9876543233',
    email: 'deepak@unitech.com',
    description: 'Apartment complex construction.',
  },
  {
    siteCode: 'SITE025',
    siteName: 'Power Substation',
    clientName: 'Power Grid',
    projectName: 'Power Grid Substation Noida',
    address: 'Noida Sector 137',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201305',
    contactPerson: 'Sanjay Pandey',
    contactNumber: '9876543234',
    email: 'sanjay@powergrid.in',
    description: 'Electrical substation construction.',
  },
  {
    siteCode: 'SITE026',
    siteName: 'Road Expansion Project',
    clientName: 'NHAI',
    projectName: 'Expressway Widening Phase 2',
    address: 'Delhi-Mumbai Expressway',
    city: 'Gurgaon',
    district: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    contactPerson: 'Manoj Agarwal',
    contactNumber: '9876543235',
    email: 'manoj@nhai.gov.in',
    description: 'Expressway widening project.',
  },
  {
    siteCode: 'SITE027',
    siteName: 'Cold Storage Facility',
    clientName: 'Mother Dairy',
    projectName: 'Mother Dairy Cold Storage',
    address: 'Wazirabad, Delhi',
    city: 'Delhi',
    district: 'North Delhi',
    state: 'Delhi',
    pincode: '110006',
    contactPerson: 'Rakesh Goyal',
    contactNumber: '9876543236',
    email: 'rakesh@motherdairy.com',
    description: 'Cold storage facility construction.',
  },
  {
    siteCode: 'SITE028',
    siteName: 'Textile Mill',
    clientName: 'Reliance Textiles',
    projectName: 'Reliance Textile Mill',
    address: 'Faridabad Industrial Area',
    city: 'Faridabad',
    district: 'Faridabad',
    state: 'Haryana',
    pincode: '121001',
    contactPerson: 'Mukesh Agarwal',
    contactNumber: '9876543237',
    email: 'mukesh@reliancetext.com',
    description: 'Textile mill construction project.',
  },
  {
    siteCode: 'SITE029',
    siteName: 'Tech Hub Building',
    clientName: 'TCS',
    projectName: 'TCS Tech Hub Noida',
    address: 'Noida Sector 135',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    pincode: '201315',
    contactPerson: 'Vikram Joshi',
    contactNumber: '9876543238',
    email: 'vikram@tcs.com',
    description: 'Technology hub building construction.',
  },
  {
    siteCode: 'SITE030',
    siteName: 'Waste Treatment Center',
    clientName: 'Delhi Municipal Corp',
    projectName: 'Waste Treatment Plant Ghazipur',
    address: 'Ghazipur, Delhi',
    city: 'Delhi',
    district: 'East Delhi',
    state: 'Delhi',
    pincode: '110096',
    contactPerson: 'Pramod Sharma',
    contactNumber: '9876543239',
    email: 'pramod@mcd.gov.in',
    description: 'Waste treatment center construction.',
  },
];

const seedSites = async () => {
  logger.info('Seeding sites...');

  const adminUser = await User.findOne({ email: 'admin@contractor.com', isDeleted: false });
  const createdBy = adminUser ? adminUser._id : null;

  let createdCount = 0;

  for (const siteData of SITES) {
    const existingSite = await Site.findOne({
      $or: [
        { siteCode: siteData.siteCode },
        { siteName: siteData.siteName },
      ],
      isDeleted: false,
    });

    if (existingSite) {
      continue;
    }

    const site = await Site.create({
      ...siteData,
      startDate: faker.date.past({ years: 2, refDate: '2026-01-01' }),
      endDate: faker.date.future({ years: 1, refDate: '2026-01-01' }),
      status: Math.random() > 0.2 ? 'ACTIVE' : 'INACTIVE',
      createdBy,
      updatedBy: createdBy,
    });

    createdCount++;
  }

  logger.info(`Sites created: ${createdCount}`);
  return { count: createdCount };
};

export default seedSites;